Repository ejgallego/rocq-lsp, pull requests merged in 2022-10, with the labels that each got.

#47 [build] Also build ltac2 in the composed setup.
  Makefile
  coq-lsp.opam
Labels: part: build

#44 [nix] add nix flake
  README.md
  flake.lock
  flake.nix
Labels: part: build

#59 [example] add 2048 example
  examples/T2048.v
Labels: part: test-suite

#61 [stats] Add quick memory stats to sentence information.
  fleche/config.ml
  fleche/doc.ml
  fleche/stats.mli
Labels: enhancement

#63 [diags] Send processing diagnostics if in eager mode.
  fleche/doc.ml
Labels: enhancement
