Repository ejgallego/rocq-lsp, pull requests merged in 2023-01, with the labels that each got.

#85 doc: Detail Nix usage in README.md
  README.md
Labels: part: documentation

#140 workspace: add parsing for -noinit, -indices-matter, -impredicative-set
  CHANGES.md
  coq/workspace.ml
  coq/workspace.mli
  fleche/doc.ml
Labels: needs: changes entry

#144 CHANGES: add changelog entry for #130
  CHANGES.md
Labels: part: documentation

#146 [controller] Refactor document handling
  controller/coq_lsp.ml
  etc/doc/PROTOCOL.md
Labels: part: server, kind: cleanup, kind: internal

#147 feature: add --bt flag
  CHANGES.md
  controller/coq_lsp.ml
Labels: part: server, kind: internal

#128 [infoview] Show Notice feedbacks on panel instead of as diagnostics
  CHANGES.md
  controller/coq_lsp.ml
  editor/code/CHANGELOG.md
  editor/code/package.json
  editor/code/src/goals.ts
  fleche/config.ml
  fleche/doc.ml
  fleche/doc.mli
  fleche/info.ml
  fleche/info.mli
Labels: kind: enhancement, part: server, part: goals and info panel, kind: redesign

#134 makefile: add extension target
  Makefile
Labels: part: build, kind: internal

#148 [logging] Several tweaks to #130
  CHANGES.md
  controller/coq_lsp.ml
  fleche/debug.ml
  fleche/doc.ml
  fleche/info.ml
  fleche/io.ml
  fleche/io.mli
  fleche/memo.ml
  lsp/io.ml
  lsp/io.mli
Labels: part: server, part: protocol (LSP), kind: fix, kind: internal

#150 [coq] Workspace handling code rework
  CHANGES.md
  controller/coq_lsp.ml
  coq/init.ml
  coq/init.mli
  coq/workspace.ml
  coq/workspace.mli
  fleche/doc.ml
Labels: needs: progress, part: server, kind: fix

#145 Clean up some code, improve debug info in fleche
  fleche/doc.ml
  fleche/memo.ml
Labels: part: server, kind: internal

#151 [coq] Workspace handling code rework, part 2
  CHANGES.md
  controller/coq_lsp.ml
  coq/workspace.ml
  coq/workspace.mli
Labels: part: server, kind: fix

#118 [error recovery] Allow to admit proofs on failed `Qed`.
  CHANGES.md
  coq/state.ml
  coq/state.mli
  editor/code/package.json
  editor/code/src/client.ts
  fleche/config.ml
  fleche/doc.ml
  fleche/memo.ml
  fleche/memo.mli
Labels: kind: enhancement, part: server, kind: redesign

#155 [controller] Handle failing requests better.
  controller/coq_lsp.ml
Labels: part: server, kind: upstream, kind: internal

#154 [faq] Preliminary FAQ
  README.md
  etc/FAQ.md
Labels: part: documentation

#158 [meta] Bump coq-lsp version in server and client.
  controller/coq_lsp.ml
  editor/code/package.json
Labels: part: packaging, kind: internal

#157 [fleche] Protect Coq document creation
  controller/coq_lsp.ml
  coq/protect.ml
  coq/protect.mli
  fleche/doc.ml
  fleche/doc.mli
  fleche/memo.ml
Labels: part: server, kind: internal

#160 [coq] Protect all base API calls
  CHANGES.md
  controller/coq_lsp.ml
  coq/init.ml
  coq/init.mli
  coq/interp.ml
  coq/parsing.ml
  coq/parsing.mli
  coq/print.ml
  coq/print.mli
  coq/protect.ml
  coq/protect.mli
  coq/state.ml
  coq/state.mli
  fleche/doc.ml
  fleche/doc.mli
  fleche/info.ml
Labels: kind: enhancement, part: server, kind: upstream, kind: internal

#159 [opam] Some fixes to opam.
  README.md
  coq-lsp.opam
Labels: kind: fix, part: packaging

#166 [controller] Separate dispatching of notifications and requests
  controller/coq_lsp.ml
  lsp/base.ml
  lsp/base.mli
Labels: part: server, kind: cleanup, kind: internal

#162 [server] add version string in separate file and update version, fix bug
  controller/coq_lsp.ml
  controller/dune
  controller/version.ml
  controller/version.mli
Labels: part: server, part: protocol (custom), kind: fix, kind: internal

#167 [controller] Refactor into several files
  controller/cache.ml
  controller/cache.mli
  controller/coq_lsp.ml
  controller/doc_manager.ml
  controller/doc_manager.mli
  controller/dune
  controller/lsp_util.ml
  controller/lsp_util.mli
  controller/requests.ml
  controller/requests.mli
Labels: part: server, kind: cleanup, kind: internal

#168 [controller] Follow the initialize specification better.
  CHANGES.md
  controller/coq_lsp.ml
  coq/workspace.ml
Labels: part: server, part: protocol (LSP), kind: internal

#170 [code] Allow goals to follow selection update by a command
  CHANGES.md
  editor/code/package.json
  editor/code/src/client.ts
Labels: part: client, kind: fix

#169 [server] Warn the user of possible problems when >= 2 files are open.
  CHANGES.md
  controller/doc_manager.ml
Labels: part: server, kind: upstream, part: documentation

#141 [controller] Allow to postpone and cancel requests
  CHANGES.md
  controller/coq_lsp.ml
  controller/doc_manager.ml
  controller/doc_manager.mli
  controller/requests.ml
  controller/requests.mli
Labels: part: server, part: protocol (LSP)

#176 [fleche] Some refactoring in preparation for a more controlled interp loop
  controller/coq_lsp.ml
  controller/doc_manager.ml
  controller/doc_manager.mli
  controller/requests.ml
  coq/init.mli
  coq/interp.ml
  coq/interp.mli
  coq/parsing.mli
  coq/print.ml
  coq/print.mli
  coq/protect.ml
  coq/protect.mli
  coq/state.mli
  fleche/doc.ml
  fleche/doc.mli
  fleche/info.ml
  fleche/info.mli
  fleche/io.ml
  fleche/io.mli
  fleche/memo.ml
  fleche/memo.mli
Labels: part: server, kind: internal

#175 [goals] Send and display information about shelved and given up goals.
  CHANGES.md
  Makefile
  controller/requests.ml
  editor/code/src/goals.ts
  etc/doc/PROTOCOL.md
Labels: kind: enhancement, part: client, part: server, part: protocol (custom), part: goals and info panel, kind: HCI design

#178 [api] Improvements on Coq API encapsulation.
  coq/goals.ml
  coq/goals.mli
  coq/parsing.ml
  coq/parsing.mli
  coq/state.ml
  coq/state.mli
  fleche/doc.ml
  fleche/info.ml
Labels: part: server, kind: cleanup, kind: internal

#177 [fleche] Allow to set cutoff point.
  controller/coq_lsp.ml
  controller/doc_manager.ml
  controller/requests.ml
  coq/ast.ml
  fleche/doc.ml
  fleche/doc.mli
Labels: kind: enhancement, part: server, kind: internal

#179 [controller] Postpone position requests until doc checking catches up.
  CHANGES.md
  controller/coq_lsp.ml
  controller/doc_manager.ml
  controller/doc_manager.mli
  controller/requests.ml
  controller/requests.mli
  editor/code/package.json
  editor/code/src/client.ts
  editor/code/src/goals.ts
  fleche/debug.ml
  fleche/doc.ml
  fleche/doc.mli
  lsp/base.ml
Labels: kind: enhancement, part: server, part: protocol (LSP), kind: redesign, kind: internal

#180 [fleche] Store (and restore) global stats per-document.
  CHANGES.md
  controller/requests.ml
  fleche/doc.ml
  fleche/doc.mli
  fleche/info.ml
  fleche/info.mli
  fleche/stats.ml
  fleche/stats.mli
Labels: kind: enhancement, part: server, kind: fix, kind: internal

#184 [opam] [ci] Support for OCaml 4.11
  .github/workflows/build.yml
  CHANGES.md
  coq-lsp.opam
Labels: kind: enhancement, part: build, part: packaging, part: CI

#188 editor/code: scope keybinding alt+enter correctly
  CHANGES.md
  editor/code/package.json
Labels: part: client, kind: fix, part: goals and info panel

#199 [fleche] Cache computation of contents structure and processing
  fleche/doc.ml
  fleche/doc.mli
  fleche/types.mli
Labels: part: server, kind: cleanup, kind: internal

#171 Render goals in the webview context
  .gitignore
  CHANGES.md
  editor/code/.gitignore
  editor/code/.vscode/extensions.json
  editor/code/.vscode/tasks.json
  editor/code/.vscodeignore
  editor/code/esbuild.mjs
  editor/code/lib/types.ts
  editor/code/package-lock.json
  editor/code/package.json
  editor/code/src/client.ts
  editor/code/src/goals.ts
  editor/code/src/tsconfig.json
  editor/code/tsconfig-base.json
  editor/code/tsconfig.json
  editor/code/view/goalRender.ts
  editor/code/view/infoview.ts
  editor/code/view/media/styles.css
  editor/code/view/tsconfig.json
Labels: kind: enhancement, part: build, part: client, part: goals and info panel, kind: redesign, kind: internal

#204 [esbuild] Properly detect --watch --sourcemap=no and --minify parameters
  editor/code/esbuild.mjs
  editor/code/package.json
  editor/code/src/client.ts
Labels: part: build, part: client, kind: fix, part: packaging

#207 [controller] Some refactoring for request handling
  controller/coq_lsp.ml
  controller/doc_manager.ml
  fleche/doc.ml
  fleche/doc.mli
Labels: part: server, kind: cleanup, kind: internal

#208 [lsp] Remove noop --std argument.
  CHANGES.md
  README.md
  controller/coq_lsp.ml
  editor/code/package.json
  lsp/base.ml
  lsp/base.mli
Labels: part: server, kind: cleanup

#210 [code] Check for VSCoq and complain about a possible conflict.
  editor/code/CHANGELOG.md
  editor/code/src/client.ts
Labels: part: client, part: deps, part: documentation

#211 [code] Refactor fileProgress client logic.
  editor/code/src/client.ts
  editor/code/src/progress.ts
Labels: part: client, part: protocol (custom), kind: cleanup

#206 [README] Pass and update.
  CONTRIBUTING.md
  README.md
  etc/ContributionIdeas.md
Labels: part: documentation, kind: cleanup

#213 [code] [build] Don't include sourcemaps in marketplace package
  editor/code/.vscodeignore
  editor/code/esbuild.mjs
Labels: part: build, part: client, kind: fix, part: packaging, kind: internal

#214 [build] [code] [ci] Check TS compilation on CI.
  .github/workflows/build.yml
  Makefile
  editor/code/src/client.ts
Labels: part: build, part: client, kind: fix, part: CI

#215 [info panel] Refactor panel to proper object.
  editor/code/lib/types.ts
  editor/code/src/client.ts
  editor/code/src/goals.ts
  editor/code/view/infoview.ts
  etc/doc/PROTOCOL.md
Labels: part: client, kind: cleanup, part: goals and info panel, kind: redesign, kind: internal

#212 categorize settings
  CHANGES.md
  editor/code/package.json
Labels: kind: enhancement, part: client, kind: redesign

#218 [code] [config] Refactor config settings to their own file.
  editor/code/src/client.ts
  editor/code/src/config.ts
  editor/code/src/progress.ts
Labels: part: client, kind: cleanup, kind: internal

#222 [controller] Scope request error handling properly.
  controller/coq_lsp.ml
Labels: part: server, kind: fix, kind: internal

#221 [infoview] Move into its own subdir, prepare for more views.
  editor/code/.vscodeignore
  editor/code/esbuild.mjs
  editor/code/src/goals.ts
  editor/code/tsconfig-base.json
  editor/code/tsconfig.json
  editor/code/views/info/goalRender.ts
  editor/code/views/info/index.ts
  editor/code/views/info/media/styles.css
  editor/code/views/info/tsconfig.json
Labels: part: build, part: client, kind: cleanup, part: goals and info panel, kind: internal

#220 [protocol] [doc] Version protocol extensions by release.
  etc/doc/PROTOCOL.md
Labels: part: protocol (custom), part: documentation, kind: cleanup

#226 [doc_manager] Allow to postpone more than one position request.
  controller/coq_lsp.ml
  controller/doc_manager.ml
  controller/doc_manager.mli
  controller/dune
  controller/rq_init.ml
  controller/rq_init.mli
Labels: kind: enhancement, part: server, part: protocol (LSP), kind: internal

#229 [doc manager] Remove [yield] from [Doc_manager.check]
  controller/coq_lsp.ml
  controller/doc_manager.ml
  controller/doc_manager.mli
Labels: part: server, kind: cleanup, kind: redesign, kind: internal

#237 [server] Improve `GoalAnswer` request response.
  CHANGES.md
  controller/requests.ml
  editor/code/lib/types.ts
  editor/code/src/goals.ts
  editor/code/views/info/goalRender.ts
  editor/code/views/info/index.ts
  etc/doc/PROTOCOL.md
Labels: kind: enhancement, part: server, part: protocol (custom), kind: fix, part: goals and info panel

#240 Pff.v: update to upstream version
  examples/Pff.v
Labels: part: test-suite, kind: internal

#239 T2048.v: update to upstream version
  examples/T2048.v
Labels: part: test-suite, kind: internal

#238 Rtrigo1.v: update to upstream version
  examples/Rtrigo1.v
Labels: part: test-suite, kind: internal

#241 Fix typo in -impredicative-set parsing
  CHANGES.md
  coq/workspace.ml
Labels: kind: fix, needs: changes entry

#242 infoview: preserve focus when creating Webview panel
  CHANGES.md
  editor/code/src/goals.ts
Labels: part: client, kind: fix

#247 [workspace] Allow to enable backtraces on a workspace-basis
  controller/coq_lsp.ml
  coq/workspace.ml
  coq/workspace.mli
Labels: part: server, kind: internal

#223 [infoview] Port to React
  CHANGES.md
  editor/code/esbuild.mjs
  editor/code/lib/types.ts
  editor/code/package-lock.json
  editor/code/package.json
  editor/code/src/goals.ts
  editor/code/views/info/Info.tsx
  editor/code/views/info/goalRender.ts
  editor/code/views/info/index.ts
  editor/code/views/info/index.tsx
  editor/code/views/info/media/info.css
  editor/code/views/info/media/styles.css
  editor/code/views/info/tsconfig.json
Labels: kind: enhancement, part: build, part: client, part: protocol (custom), part: packaging, part: deps, kind: cleanup, part: goals and info panel, kind: internal

#248 [config] Add debug client option.
  CHANGES.md
  controller/coq_lsp.ml
  editor/code/package.json
  editor/code/src/config.ts
  fleche/config.ml
Labels: kind: enhancement, part: client, part: server, part: protocol (custom), kind: internal

#250 [Makefile] coq configure prefix and add nostdlib make
  Makefile
Labels: part: build, kind: internal

#249 [ci] Add OCaml 5 to CI.
  .github/workflows/build.yml
Labels: part: CI

#256 [lsp] More rework of LSP serialization.
  controller/requests.ml
  coq/goals.ml
  coq/goals.mli
  fleche/doc.ml
  fleche/types.ml
  fleche/types.mli
  lsp/jCoq.ml
  lsp/jFleche.ml
  lsp/jFleche.mli
Labels: part: server, part: protocol (custom), part: protocol (LSP), kind: cleanup, kind: internal

#257 [doc] Make global stats structure incremental
  controller/requests.ml
  fleche/doc.ml
  fleche/doc.mli
Labels: part: server, kind: fix, kind: cleanup, kind: internal

#260 [coq] Fix libname calculation.
  CHANGES.md
  coq/init.ml
  coq/init.mli
  coq/workspace.ml
  coq/workspace.mli
  fleche/doc.ml
  lsp/base.ml
Labels: part: server, kind: fix, kind: upstream, part: workspace setup

#258 [lsp] Fix serialization of diagnostics
  lsp/jFleche.ml
Labels: part: server, part: protocol (LSP), kind: fix, kind: internal

#261 [workspace] use `rootPath` to detect `_CoqProject` file.
  CHANGES.md
  controller/coq_lsp.ml
  coq/workspace.ml
  coq/workspace.mli
Labels: part: server, part: protocol (LSP), kind: fix, part: workspace setup

#265 [completion] Return last valid index when request is out-of-bounds
  CHANGES.md
  controller/rq_completion.ml
  fleche/utf8.ml
Labels: part: server, part: protocol (LSP), kind: fix

#266 [code] [changelog] Update client changelog.
  editor/code/CHANGELOG.md
Labels: part: client, part: documentation, kind: meta

#268 [version] Bump to 0.1.5
  CHANGES.md
  controller/version.ml
  editor/code/package-lock.json
  editor/code/package.json
Labels: part: packaging, kind: meta

#270 [doc] [completion] Improve UTF-8 and position validation
  controller/rq_completion.ml
  fleche/coq_utils.ml
  fleche/doc.ml
  fleche/utf8.ml
  fleche/utf8.mli
Labels: part: server, kind: fix, kind: internal

#259 [doc] Improvements to contributing guide
  CONTRIBUTING.md
  README.md
  etc/ContributionIdeas.md
Labels: kind: enhancement, part: documentation

#272 [info] Fix messages panel rendering after port to react.
  CHANGES.md
  editor/code/views/info/Info.tsx
Labels: part: client, kind: fix, part: goals and info panel, kind: HCI design

#271 [lsp] Make sure ranges are serialized to LSP types
  CHANGES.md
  lsp/jFleche.ml
Labels: part: server, part: protocol (LSP), kind: fix, kind: internal

#274 [controller] Move platform-independent bits to controller library.
  controller/coq_lsp.ml
  controller/coq_lsp.mli
  controller/dune
  controller/lsp_core.ml
  controller/lsp_core.mli
  lsp/io.ml
  lsp/io.mli
Labels: part: server, kind: cleanup, kind: redesign, kind: internal, part: web worker
