Repository ejgallego/rocq-lsp, pull requests merged in 2023-10, with the labels that each got.

#562 [hover] Refactor providers into plugins, add basic notation display.
  CHANGES.md
  controller/rq_common.ml
  controller/rq_common.mli
  controller/rq_definition.ml
  controller/rq_hover.ml
  controller/rq_hover.mli
Labels: kind: enhancement, part: lsp server, kind: internal, lsp: hover, part: plugin API

#565 [client] Update vscode client and misc js packages
  CHANGES.md
  editor/code/package-lock.json
  editor/code/package.json
  editor/code/views/info/tsconfig.json
Labels: kind: enhancement, part: client (VSCode), part: deps, kind: upstream, kind: internal, part: upstream

#566 [fleche] Implement document scheduler
  CHANGES.md
  examples/Pff.v
  fleche/theory.ml
  fleche/theory.mli
  lang/lUri.ml
  lang/lUri.mli
Labels: kind: enhancement, part: flèche

#544 chore: update flake
  flake.lock
  flake.nix
  test/server/src/Check.test.ts
  test/server/src/LanguageServer.ts
  test/server/src/Lifecycle.test.ts
Labels: kind: internal

#567 [fleche] [error] Detect Qed based on buffer contents
  CHANGES.md
  examples/qed_lex.v
  fleche/doc.ml
Labels: kind: enhancement, part: flèche, part: error recovery

#543 [dev] Update ocamlformat to 0.26.0
  .ocamlformat
  controller/rq_init.ml
  coq/loader.ml
  fleche/contents.ml
  fleche/doc.ml
Labels: part: build, kind: internal

#568 [build] Don't use `-rectypes` on compilation.
  dune
Labels: part: build, kind: internal

#573 [README] [nix] Add changes + tweak on the README.
  CHANGES.md
  README.md
Labels: kind: enhancement, part: documentation, os: nix

#575 [goals] Remove duplicate call to Info.find
  controller/rq_goals.ml
  controller/rq_hover.ml
  fleche/info.ml
  fleche/info.mli
Labels: part: lsp server, kind: cleanup, kind: internal

#577 [fleche] Small refactoring on error recovery code.
  fleche/doc.ml
Labels: kind: cleanup, kind: internal

#581 [workspace] Support `-rifrom` option.
  CHANGES.md
  compiler/fcc.ml
  controller/coq_lsp.ml
  coq/workspace.ml
  coq/workspace.mli
  examples/lists.mv
  test/CoqProject/_CoqProject
  test/CoqProject/test.v
Labels: kind: enhancement, part: lsp server, kind: upstream, part: workspace setup, part: compiler

#576 [client] [vscode] Export Query Goals API
  CHANGES.md
  README.md
  editor/code/src/client.ts
  editor/code/src/goals.ts
  editor/code/src/node.ts
Labels: kind: enhancement, part: client (VSCode), part: plugin API

#584 [meta] Bump version to 0.1.8
  CHANGES.md
  editor/code/package.json
  fleche/version.ml
Labels: part: client (VSCode), part: lsp server, kind: meta

#583 [workspace] [windows] Tolerate better Windows paths with mixed path separators
  CHANGES.md
  controller/lsp_core.ml
Labels: part: lsp server, kind: fix, part: workspace setup, platform: windows

#586 [info view] Adjust breaks in errors and messages panels.
  CHANGES.md
  editor/code/views/info/ErrorBrowser.tsx
  editor/code/views/info/Message.tsx
  editor/code/views/info/media/goals.css
  examples/record_print.v
Labels: part: client (VSCode), kind: fix, part: goals and info panel, part: pp printer

#585 [meta] Bump version to 0.1.9-dev
  editor/code/package.json
  fleche/version.ml
Labels: part: client (VSCode), part: lsp server, kind: internal, kind: meta

#588 [hover] New option `show_loc_info_on_hover` to display parsing debug info.
  CHANGES.md
  controller/rq_hover.ml
  editor/code/package.json
  editor/code/src/config.ts
  fleche/config.ml
Labels: kind: enhancement, part: client (VSCode), part: lsp server, part: protocol (custom), kind: fix, kind: cleanup, part: config

#589 [readme] Add info about our backported branches with Coq fixes
  README.md
Labels: kind: upstream, part: documentation, kind: cleanup, kind: upstream-bug

#591 [hover] [api] Allow hover access to full document.
  CHANGES.md
  controller/rq_hover.ml
  controller/rq_hover.mli
Labels: kind: enhancement, lsp: hover, part: plugin API
