Repository ejgallego/rocq-lsp, pull requests merged in 2023-03, with the labels that each got.

#439 [meta] Bump version to 0.1.7
  controller/version.ml
  editor/code/package.json
Labels: part: packaging, kind: meta

#438 [goals] Fix goals_after_tactic option retrieval.
  CHANGES.md
  controller/rq_goals.ml
Labels: kind: bug, part: server, kind: fix, needs: test-case, lsp: goals

#442 doc: Restructure contributing guide (server+client guides)
  CONTRIBUTING.md
Labels: kind: enhancement, part: documentation

#444 [workspace] Fix message about workspace detection
  CHANGES.md
  coq/workspace.ml
Labels: kind: bug, part: server, part: protocol (LSP), kind: fix, part: workspace setup

#262 [info panel] Program Obligation support in infoview
  CHANGES.md
  controller/rq_goals.ml
  coq/state.ml
  coq/state.mli
  editor/code/lib/types.ts
  editor/code/views/info/Info.tsx
  editor/code/views/info/Loc.tsx
  editor/code/views/info/Program.tsx
  etc/doc/PROTOCOL.md
  examples/obligations.v
  fleche/info.ml
  fleche/info.mli
  lsp/jCoq.ml
  lsp/jFleche.ml
  lsp/jFleche.mli
Labels: kind: enhancement, part: client, part: server, part: protocol (custom), kind: upstream, part: goals and info panel, kind: redesign, kind: HCI design

#181 [code] [protocol] Add notification about document perf data.
  CHANGES.md
  controller/doc_manager.ml
  controller/perf.ml
  controller/perf.mli
  coq/ast.ml
  editor/code/esbuild.mjs
  editor/code/lib/types.ts
  editor/code/package-lock.json
  editor/code/package.json
  editor/code/src/client.ts
  editor/code/src/perf.ts
  editor/code/tsconfig.json
  editor/code/views/info/Info.tsx
  editor/code/views/perf/App.css
  editor/code/views/perf/App.tsx
  editor/code/views/perf/index.tsx
  editor/code/views/perf/media/styles.css
  editor/code/views/perf/tsconfig.json
  etc/doc/PROTOCOL.md
  fleche/doc.ml
  fleche/memo.ml
  fleche/memo.mli
  fleche/stats.ml
  fleche/stats.mli
  lsp/jFleche.ml
  lsp/jFleche.mli
Labels: kind: enhancement, part: client, part: server, part: protocol (custom), kind: HCI design

#450 [lsp] Generalize LSP init loop to support async IO.
  controller/coq_lsp.ml
  controller/lsp_core.ml
  controller/lsp_core.mli
Labels: part: server, kind: cleanup, kind: internal

#451 [coq] Don't expose feedback to clients.
  controller/coq_lsp.ml
  coq/init.ml
  coq/init.mli
Labels: part: server, kind: upstream, kind: cleanup, kind: internal

#453 [init] Be more resilient to input, fix bug on workspace parsing
  CHANGES.md
  controller/lsp_core.ml
  controller/rq_init.ml
  lsp/io.ml
  lsp/io.mli
Labels: part: server, part: protocol (LSP), kind: fix, needs: test-case

#462 meta: add .gitattributes file
  .gitattributes
Labels: kind: meta

#464 [doc manager] Move postponement logic to document manager.
  controller/doc_manager.ml
  controller/doc_manager.mli
  controller/lsp_core.ml
  controller/request.ml
  controller/request.mli
Labels: kind: enhancement, part: server, kind: cleanup, kind: internal

#469 Added required support for ViZX Extension
  editor/code/src/goals.ts
Labels: part: client, kind: internal, part: plugin API

#470 [protocol] Include goal output type in goals request
  CHANGES.md
  controller/lsp_core.ml
  controller/rq_goals.ml
  controller/rq_goals.mli
  editor/code/lib/types.ts
  editor/code/src/goals.ts
  etc/doc/PROTOCOL.md
Labels: kind: enhancement, part: protocol (custom)

#471 [controller] [native] New parameter --idle-delay
  CHANGES.md
  controller/coq_lsp.ml
Labels: kind: enhancement, part: server, kind: internal
