Repository ejgallego/rocq-lsp, pull requests merged in 2023-02, with the labels that each got.

#276 Adapt w.r.t. coq/coq#17170.
  coq/goals.ml
Labels: part: server, kind: upstream, kind: internal

#277 infoview/goals: fix off-by-one error in goal numbering
  CHANGES.md
  editor/code/views/info/Info.tsx
Labels: part: client, kind: fix

#280 [fleche] [markdown] Require Coq markdown snippets to use ```coq
  CHANGES.md
  README.md
  examples/lists.mv
  fleche/doc.ml
  fleche/doc.mli
Labels: part: server, kind: internal

#285 [info] Split React components into proper modules
  editor/code/views/info/CoqPp.tsx
  editor/code/views/info/Details.tsx
  editor/code/views/info/Goals.tsx
  editor/code/views/info/Info.tsx
  editor/code/views/info/Message.tsx
Labels: part: client, kind: cleanup, part: goals and info panel, kind: internal

#286 [fleche] Generalize contents type
  controller/doc_manager.ml
  controller/doc_manager.mli
  controller/lsp_core.ml
  coq/protect.ml
  coq/protect.mli
  examples/exerciseTest.wpn
  fleche/contents.ml
  fleche/contents.mli
  fleche/doc.ml
  fleche/doc.mli
Labels: kind: enhancement, part: server, kind: cleanup, kind: internal

#292 [fleche] First version of the language abstraction library.
  controller/coq_lsp.ml
  controller/doc_manager.ml
  controller/requests.ml
  controller/rq_completion.ml
  fleche/contents.ml
  fleche/contents.mli
  fleche/coq_utils.ml
  fleche/coq_utils.mli
  fleche/doc.ml
  fleche/doc.mli
  fleche/dune
  fleche/info.ml
  fleche/info.mli
  fleche/io.ml
  fleche/io.mli
  fleche/progress.ml
  fleche/types.ml
  fleche/types.mli
  lang/diagnostic.ml
  lang/diagnostic.mli
  lang/dune
  lang/point.ml
  lang/point.mli
  lang/range.ml
  lang/range.mli
  lsp/dune
  lsp/jFleche.ml
  lsp/jFleche.mli
  lsp/jLang.ml
  lsp/jLang.mli
Labels: part: server, kind: cleanup, kind: internal

#295 [lsq_init] `rootPath` is optional, `rootUri` has precedence.
  CHANGES.md
  controller/lsp_core.ml
  controller/rq_init.ml
  controller/rq_init.mli
Labels: part: server, part: protocol (LSP), kind: fix, kind: internal

#297 [controller] Refactor requests to their own module.
  controller/lsp_core.ml
  controller/requests.ml
  controller/requests.mli
  controller/rq_goals.ml
  controller/rq_goals.mli
  controller/rq_hover.ml
  controller/rq_hover.mli
Labels: part: server, kind: cleanup, kind: internal

#298 [doc] Add information about accepted URI types.
  CHANGES.md
  coq/goals.ml
  coq/goals.mli
  etc/doc/PROTOCOL.md
Labels: part: protocol (custom), part: documentation

#289 [info panel] Some more refactoring and splitting of components, css
  editor/code/views/info/ErrorBrowser.tsx
  editor/code/views/info/FileInfo.tsx
  editor/code/views/info/Goals.tsx
  editor/code/views/info/Info.tsx
  editor/code/views/info/Messages.tsx
  editor/code/views/info/index.tsx
  editor/code/views/info/media/goals.css
  editor/code/views/info/media/index.css
  editor/code/views/info/media/messages.css
Labels: part: client, kind: cleanup, part: goals and info panel, kind: internal

#287 [fleche] Reject opening multiple Coq documents for buggy Coq versions.
  CHANGES.md
  README.md
  controller/doc_manager.ml
  controller/lsp_core.ml
  fleche/doc.ml
  fleche/doc.mli
Labels: part: server, kind: fix, kind: upstream, kind: internal

#301 [server] [lsp] Fix bug when parsing client option for unicode completion
  CHANGES.md
  lsp/jFleche.ml
Labels: part: server, part: protocol (custom), part: protocol (LSP), kind: fix, kind: internal

#303 [fleche] Stop checking a document when there are too many errors.
  CHANGES.md
  editor/code/package.json
  editor/code/src/config.ts
  fleche/config.ml
  fleche/doc.ml
  lang/diagnostic.ml
  lang/diagnostic.mli
Labels: kind: enhancement, part: server

#302 workspace: support unicode filenames
  CHANGES.md
  coq-lsp.opam
  coq/dune
  coq/workspace.ml
Labels: part: server, part: protocol (LSP), kind: fix

#307 [code] Improve markdown syntax highglighting
  editor/code/CHANGELOG.md
  editor/code/package.json
  editor/code/src/client.ts
  editor/code/src/progress.ts
  editor/code/syntaxes/coqmarkdown.json
  editor/code/syntaxes/markdown-coq-codeblock.json
Labels: kind: enhancement, part: client, kind: HCI design

#309 Enable find widget in goal panel
  CHANGES.md
  editor/code/src/goals.ts
Labels: kind: enhancement, part: client, part: goals and info panel, kind: HCI design

#306 [contents] Add preliminary waterproof parser.
  CHANGES.md
  coq-lsp.opam
  dune-project
  examples/exerciseTest.wpn
  fleche/contents.ml
  fleche/dune
  fleche/waterproof/dune
  fleche/waterproof/json.ml
  fleche/waterproof/ljson.mly
  fleche/waterproof/tjson.mll
Labels: kind: enhancement, part: server, part: protocol (LSP)

#314 [messages] Enable display of info and debug messages.
  CHANGES.md
  controller/coq_lsp.ml
  controller/rq_goals.ml
  editor/code/views/info/media/messages.css
  fleche/doc.ml
Labels: kind: enhancement, part: server, part: protocol (custom), kind: fix, kind: HCI design

#290 [goals] Adapt jsCoq goal printing code to VS Code / React
  CHANGES.md
  editor/code/views/info/CoqPp.tsx
  editor/code/views/info/Details.tsx
  editor/code/views/info/Goals.tsx
  editor/code/views/info/media/coqpp.css
  editor/code/views/info/media/goals.css
  examples/goals.v
  lsp/jCoq.ml
  lsp/jFleche.ml
  lsp/jFleche.mli
Labels: kind: enhancement, part: client, kind: fix, kind: cleanup, part: goals and info panel, kind: HCI design

#311 [CONTRIBUTING] Clarify changelog process.
  CONTRIBUTING.md
Labels: part: documentation, kind: meta

#315 [messages] Print warnings in info panel
  CHANGES.md
  controller/rq_goals.ml
  editor/code/lib/types.ts
  editor/code/views/info/Message.tsx
  editor/code/views/info/Messages.tsx
  etc/doc/PROTOCOL.md
  fleche/doc.ml
  lsp/jFleche.ml
  lsp/jFleche.mli
Labels: kind: enhancement, part: server, part: protocol (custom), kind: HCI design

#174 [info] Improve `documentSymbol` request to return extended info.
  CHANGES.md
  controller/lsp_core.ml
  controller/requests.ml
  controller/requests.mli
  controller/rq_completion.ml
  controller/rq_symbols.ml
  controller/rq_symbols.mli
  coq/ast.ml
  coq/ast.mli
  examples/documentSymbol.v
  examples/ex0.v
  fleche/doc.ml
  fleche/doc.mli
  lsp/jFleche.ml
  lsp/jFleche.mli
Labels: kind: enhancement, part: server, part: protocol (LSP), kind: HCI design

#320 [fleche] Allow error recovery to execute dynamic commands
  CHANGES.md
  coq/protect.ml
  coq/protect.mli
  coq/state.ml
  coq/state.mli
  fleche/doc.ml
  fleche/memo.mli
Labels: kind: enhancement, part: server, kind: internal

#319 [doc] [error] Auto-admit bullets on new bullet error.
  CHANGES.md
  coq/protect.ml
  coq/protect.mli
  coq/state.ml
  coq/state.mli
  examples/goals.v
  fleche/doc.ml
Labels: kind: enhancement, part: server, kind: internal

#329 [documentSymbol] Add some missing `detail` fields
  coq/ast.ml
  fleche/doc.ml
Labels: kind: enhancement, part: server, part: protocol (LSP)

#337 [fleche] [info] Store Ast info incrementally
  CHANGES.md
  controller/lsp_core.ml
  controller/requests.ml
  controller/requests.mli
  controller/rq_completion.ml
  controller/rq_symbols.ml
  coq/ast.ml
  coq/ast.mli
  coq/utf8.ml
  coq/utf8.mli
  coq/utils.ml
  coq/utils.mli
  examples/Rtrigo1.v
  fleche/contents.ml
  fleche/doc.ml
  fleche/doc.mli
  fleche/info.ml
  fleche/info.mli
Labels: kind: enhancement, part: server, kind: internal

#318 [lsp] Basic jump to definition support.
  CHANGES.md
  controller/lsp_core.ml
  controller/rq_definition.ml
  controller/rq_definition.mli
  controller/rq_init.ml
  coq/ast.ml
  coq/ast.mli
  examples/ex0.v
  fleche/doc.ml
  fleche/doc.mli
  lsp/jFleche.ml
  lsp/jFleche.mli
Labels: kind: enhancement, part: server, part: protocol (LSP)

#343 doc: README tweaks
  README.md
Labels: part: documentation, kind: cleanup

#340 [hover] Show type of definitions on hover
  CHANGES.md
  controller/rq_common.ml
  controller/rq_common.mli
  controller/rq_definition.ml
  controller/rq_hover.ml
  coq/ast.ml
  coq/ast.mli
  fleche/doc.ml
  fleche/info.ml
  fleche/info.mli
Labels: kind: enhancement, part: server, part: protocol (LSP)

#344 [code] Client changelog
  CHANGES.md
  editor/code/CHANGELOG.md
Labels: part: client, part: documentation

#143 goals: lay foundation for pretty-printing goals (#96)
  CHANGES.md
  controller/rq_goals.ml
  coq/goals.ml
  coq/goals.mli
  editor/code/lib/format-pprint/js/main.d.ts
  editor/code/lib/format-pprint/js/main.js
  editor/code/lib/types.ts
  editor/code/package-lock.json
  editor/code/package.json
  editor/code/src/config.ts
  editor/code/src/goals.ts
  editor/code/views/info/CoqPp.tsx
  editor/code/views/info/Details.tsx
  editor/code/views/info/ErrorBrowser.tsx
  editor/code/views/info/Goals.tsx
  editor/code/views/info/Info.tsx
  editor/code/views/info/Message.tsx
  editor/code/views/info/Messages.tsx
  editor/code/views/info/media/coqpp.css
  fleche/config.ml
  fleche/info.ml
  fleche/info.mli
  lsp/jCoq.ml
  lsp/jFleche.ml
  lsp/jFleche.mli
Labels: kind: enhancement, part: client, part: server, part: protocol (custom), kind: upstream, part: goals and info panel, kind: redesign

#352 [protocol] Update docs for recent work.
  etc/doc/PROTOCOL.md
Labels: part: protocol (custom), part: protocol (LSP), part: documentation

#354 [readme] Add info about Flèche, support for Coq versions, and calls.
  README.md
Labels: part: documentation, kind: meta

#357 Fix typo in keybinding config
  editor/code/package.json
Labels: part: client, kind: fix

#359 [version] Bump version, improve doc on release process.
  CONTRIBUTING.md
  controller/lsp_core.ml
  controller/version.ml
  editor/code/package.json
Labels: part: packaging, kind: internal, kind: meta

#364 [workspace] Fix handling of COQPATH and OCAMLPATH
  CHANGES.md
  coq/workspace.ml
Labels: part: server, kind: fix, kind: upstream, part: workspace setup

#351 [protocol] New request `coq/getDocument` to get serialized document.
  CHANGES.md
  controller/lsp_core.ml
  controller/rq_document.ml
  controller/rq_document.mli
  editor/code/lib/types.ts
  editor/code/package.json
  editor/code/src/client.ts
  etc/doc/PROTOCOL.md
  lsp/jCoq.ml
  lsp/jFleche.ml
  lsp/jFleche.mli
Labels: kind: enhancement, part: server, part: protocol (custom)

#365 [code] Option to ignore .vo files automatically
  CHANGES.md
  editor/code/package.json
  editor/code/src/client.ts
Labels: kind: enhancement, part: client

#369 [doc] Refactor find_proof into ast finding + action
  fleche/doc.ml
Labels: part: server, kind: cleanup, kind: internal

#370 [Nix] add nodejs to flake and ignore nix/profiles directory
  .gitignore
  CONTRIBUTING.md
  flake.nix
Labels: kind: internal, kind: meta

#360 [misc] Use dune build info for refined version view.
  controller/dune
  controller/lsp_core.ml
  coq-lsp.opam
  flake.nix
Labels: kind: enhancement, part: build, part: server, part: deps, kind: internal

#373 [lsp] Add progress, partial work, and pull diagnostics datatypes
  controller/rq_completion.ml
  controller/rq_definition.ml
  controller/rq_hover.ml
  controller/rq_symbols.ml
  lsp/base.ml
  lsp/base.mli
  lsp/core.ml
  lsp/core.mli
  lsp/jCoq.ml
  lsp/jFleche.ml
  lsp/jFleche.mli
  lsp/jLang.ml
  lsp/jLang.mli
Labels: part: server, part: protocol (custom), part: protocol (LSP), kind: cleanup, kind: internal

#374 [lsp] [controller] Add support for workspace folders
  CHANGES.md
  controller/coq_lsp.ml
  controller/lsp_core.ml
  controller/lsp_core.mli
  controller/rq_init.ml
  controller/rq_init.mli
  lsp/workspace.ml
  lsp/workspace.mli
Labels: kind: enhancement, part: server, part: protocol (LSP), part: workspace setup

#376 [lsp] Fix bug on request / notification parsing
  lsp/base.ml
Labels: part: server, part: protocol (LSP), kind: fix, kind: internal

#377 [code] Add commands to start / stop the server
  CHANGES.md
  editor/code/package.json
  editor/code/src/client.ts
Labels: kind: enhancement, part: client

#375 [controller] Fix bug where the controller was not exiting
  CHANGES.md
  controller/coq_lsp.ml
  controller/lsp_core.ml
  editor/code/package-lock.json
  lsp/io.ml
  lsp/io.mli
Labels: part: server, part: protocol (LSP), kind: fix, kind: internal

#356 test: lay the foundation for testing with node
  CHANGES.md
  controller/lsp_core.ml
  test/.gitignore
  test/.vscode/launch.json
  test/jest.config.js
  test/package-lock.json
  test/package.json
  test/src/LanguageServer.ts
  test/src/Lifecycle.test.ts
  test/tsconfig.json
Labels: kind: enhancement, part: build, part: test-suite, part: server

#129 fleche, editor: strip Ok_diagnostic feature
  CHANGES.md
  editor/code/package.json
  editor/code/src/config.ts
  fleche/config.ml
  fleche/doc.ml
Labels: part: server, part: protocol (LSP), kind: cleanup

#379 [doc] Document workspace folders PR (#374)
  README.md
  etc/doc/PROTOCOL.md
Labels: kind: fix, part: documentation

#380 [fleche] Cache document creation
  controller/cache.ml
  coq/interp.ml
  coq/interp.mli
  coq/workspace.ml
  coq/workspace.mli
  fleche/doc.ml
  fleche/doc.mli
  fleche/memo.ml
  fleche/memo.mli
  lang/lUri.ml
  lang/lUri.mli
Labels: kind: enhancement, part: server, part: protocol (LSP), kind: internal

#384 [hover] Print without parenthesis, also print abbreviations
  CHANGES.md
  controller/rq_hover.ml
Labels: kind: enhancement, part: goals and info panel

#382 [readme] Add Coqtail branch.
  README.md
Labels: kind: enhancement, part: documentation

#385 [nit] Scan also identifiers with doc, Coq's "qualids"
  CHANGES.md
  controller/rq_common.ml
Labels: kind: enhancement, part: server, part: protocol (LSP), kind: fix, kind: upstream

#383 [code] Update to language-client 8.1.0
  CHANGES.md
  README.md
  editor/code/package-lock.json
  editor/code/package.json
Labels: part: client, part: protocol (LSP), kind: fix, part: deps

#390 [fleche] Fix typo on max_errors checking
  CHANGES.md
  lang/diagnostic.ml
Labels: kind: bug, part: server, kind: internal

#391 [hover] Fix precedence of hypothesis vs globals.
  CHANGES.md
  controller/rq_hover.ml
Labels: part: server, kind: fix, lsp: hover

#395 [fleche] Add children info to the table-of-contents
  CHANGES.md
  fleche/doc.ml
Labels: kind: enhancement, part: server, part: protocol (LSP)

#396 [coq] Invalidate vernacstate cache on exception
  CHANGES.md
  coq/protect.ml
Labels: part: server, kind: fix, kind: upstream, kind: internal

#378 [code] Provide status bar button to stop / start the server.
  CHANGES.md
  README.md
  editor/code/package.json
  editor/code/src/client.ts
  editor/code/src/goals.ts
  editor/code/src/progress.ts
  editor/code/views/info/Info.tsx
Labels: kind: enhancement, part: client, kind: HCI design

#402 [infoview] Pass key to label list
  editor/code/views/info/Goals.tsx
Labels: part: client, kind: fix, part: goals and info panel, kind: internal

#403 [coq] [workspace] [init] Recognize COQLIB and COQCORELIB
  CHANGES.md
  controller/coq_lsp.ml
  coq/workspace.ml
  coq/workspace.mli
Labels: kind: enhancement, part: server, kind: fix, part: packaging, kind: upstream

#404 [doc] Minimal SerAPI migration guide.
  README.md
  etc/SerAPI.md
Labels: kind: enhancement, part: documentation

#405 [ci] Windows build
  .github/workflows/build.yml
Labels: part: CI, platform: windows

#406 doc: minor tweaks
  README.md
Labels: part: documentation

#407 emojify rest of readme
  README.md
Labels: part: documentation

#408 [windows] Patches and instructions for windows install
  CHANGES.md
  README.md
  controller/coq_lsp.ml
  controller/rq_lens.ml
  coq/workspace.ml
  coq/workspace.mli
Labels: kind: enhancement, part: server, kind: fix, kind: upstream, part: documentation, kind: internal, platform: windows

#409 ci: add jest-based testing
  .github/workflows/build.yml
  Makefile
Labels: kind: enhancement, part: server, part: CI, needs: testing

#410 [goal view] Scroll into active goal.
  CHANGES.md
  editor/code/views/info/Goals.tsx
Labels: kind: enhancement, part: goals and info panel, kind: HCI design

#411 [client] Server status icon will now react properly to fatal server errors
  CHANGES.md
  editor/code/src/client.ts
Labels: kind: enhancement, part: client, kind: fix

#412 [hover] Info on memory and time is now disabled by default
  CHANGES.md
  controller/rq_hover.ml
  editor/code/package.json
  editor/code/src/config.ts
  fleche/config.ml
Labels: kind: enhancement, part: client, part: server, part: protocol (LSP), kind: cleanup, kind: HCI design, lsp: hover

#413 [controller] Refactoring of request interface
  controller/lsp_core.ml
  controller/request.ml
  controller/request.mli
  controller/rq_completion.ml
  controller/rq_completion.mli
  controller/rq_definition.ml
  controller/rq_definition.mli
  controller/rq_document.ml
  controller/rq_document.mli
  controller/rq_goals.ml
  controller/rq_goals.mli
  controller/rq_hover.ml
  controller/rq_hover.mli
  controller/rq_lens.ml
  controller/rq_lens.mli
  controller/rq_symbols.ml
  controller/rq_symbols.mli
Labels: part: server, kind: cleanup, kind: internal

#414 doc_manager: diagnostic with severity 0 is forbidden by lsp
  controller/doc_manager.ml
Labels: part: server, part: protocol (LSP), kind: fix, kind: internal

#417 [server] Add a command to save a .vo file.
  CHANGES.md
  README.md
  controller/lsp_core.ml
  controller/rq_save.ml
  coq/save.ml
  coq/save.mli
  coq/workspace.mli
  editor/code/lib/types.ts
  editor/code/package.json
  editor/code/src/client.ts
  editor/code/src/config.ts
  etc/doc/PROTOCOL.md
  fleche/doc.ml
  fleche/doc.mli
Labels: kind: enhancement, part: client, part: server, part: protocol (custom), kind: upstream, kind: internal

#418 [doc] Add release notes dir.
  CHANGES.md
  editor/code/CHANGELOG.md
  etc/release_notes/README.md
  etc/release_notes/v0.1.0.md
  etc/release_notes/v0.1.2.md
  etc/release_notes/v0.1.4.md
  etc/release_notes/v0.1.5.md
  etc/release_notes/v0.1.6.md
Labels: kind: enhancement, part: documentation

#420 [lsp] Refactoring of parameters parsing
  controller/lsp_core.ml
  controller/rq_goals.ml
  lsp/doc.ml
  lsp/doc.mli
  lsp/jFleche.ml
  lsp/jFleche.mli
Labels: part: server, part: protocol (LSP), kind: cleanup, kind: internal

#422 [hover] Refactoring and minor fixes.
  CHANGES.md
  controller/rq_hover.ml
Labels: part: server, part: protocol (LSP), kind: fix, kind: cleanup, lsp: hover

#421 [loader] Don't fail on missing serlib plugins
  CHANGES.md
  README.md
  coq/loader.ml
Labels: part: server, kind: fix, kind: upstream, kind: internal

#423 [ci] Disable windows test until we can figure out the problem.
  .github/workflows/build.yml
Labels: part: test-suite, kind: fix, part: CI

#427 [test] Don't rebuild test/node_modules at each test iteration.
  Makefile
Labels: kind: enhancement, part: build, part: test-suite

#426 [test] Fix test exiting eagerly.
  test/package.json
  test/src/Check.test.ts
Labels: part: test-suite, kind: fix

#428 [test] More compositional test language
  test/src/Check.test.ts
  test/src/LanguageServer.ts
  test/src/Lifecycle.test.ts
Labels: kind: enhancement, part: test-suite

#429 [build] Set libdir explicitly in configure, to workaround configure bug.
  Makefile
Labels: part: build, kind: internal

#430 [code] Enable web extension support.
  CHANGES.md
  CONTRIBUTING.md
  coq/loader.ml
  editor/code/.vscode/launch.json
  editor/code/esbuild.mjs
  editor/code/package.json
  editor/code/src/browser.ts
  editor/code/src/client.ts
  editor/code/src/goals.ts
  editor/code/src/node.ts
  editor/code/src/progress.ts
Labels: kind: enhancement, part: build, part: client, part: packaging

#431 [io] Abstract IO functions
  controller/coq_lsp.ml
  controller/doc_manager.ml
  controller/doc_manager.mli
  controller/lsp_core.ml
  controller/lsp_core.mli
  fleche/doc.ml
  fleche/doc.mli
  fleche/io.ml
  fleche/io.mli
  lsp/io.ml
  lsp/io.mli
Labels: part: server, kind: cleanup, kind: redesign, kind: internal

#432 [controller] Reify yield action in the queue controller.
  controller/coq_lsp.ml
  controller/lsp_core.ml
  controller/lsp_core.mli
Labels: part: server, kind: redesign, kind: internal

#434 [workspace] Refactoring and consolidation.
  controller/coq_lsp.ml
  coq/workspace.ml
  coq/workspace.mli
Labels: part: server, kind: cleanup, kind: internal, part: workspace setup
